### ISSUE TITLE
Visualising predictions in notebook after training throws error 'function takes exactly 6 arguments (7 given)'

### ISSUE THREAD

**Issue by loicsauteur** [uhlmanngroup/splinedist#2] opened 2021-10-14 14:04 UTC
Hi

I know you still working on optimising everything, when I read about splinedist I wanted to try it out.
Running your training notebook, I came across an error in the _Visualization_ part:
**Cell**:
`Y_val_pred = [model.predict_instances(x, n_tiles=model._guess_n_tiles(x), show_tile_progress=False)[0] for x in tqdm(X_val)]`
**Error**: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19908/2124612019.py in <module>
----> 1 Y_val_pred = [model.predict_instances(x, n_tiles=model._guess_n_tiles(x), show_tile_progress=False)[0]
      2               for x in tqdm(X_val)]

~\AppData\Local\Temp/ipykernel_19908/2124612019.py in <listcomp>(.0)
----> 1 Y_val_pred = [model.predict_instances(x, n_tiles=model._guess_n_tiles(x), show_tile_progress=False)[0]
      2               for x in tqdm(X_val)]

~\Downloads\splinedist-main\splinedist\models\base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    444 
    445         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
--> 446         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
    447 
    448 

~\Downloads\splinedist-main\splinedist\models\model2d.py in _instances_from_prediction(self, img_shape, prob, dist, prob_thresh, nms_thresh, overlap_label, **nms_kwargs)
    396 
    397         coord = dist_to_coord(dist, grid=self.config.grid)
--> 398         inds = non_maximum_suppression(coord, prob, grid=self.config.grid,
    399                                        prob_thresh=prob_thresh, nms_thresh=nms_thresh, **nms_kwargs)
    400         labels = polygons_to_label(coord, prob, inds, shape=img_shape)

~\Downloads\splinedist-main\splinedist\nms.py in non_maximum_suppression(coord, prob, grid, b, nms_thresh, prob_thresh, verbose, max_bbox_search)
     60         t = time()
     61 
---> 62     survivors[ind] = c_non_max_suppression_inds(polygons.astype(np.int32),
     63                     mapping, np.float32(nms_thresh), np.int32(max_bbox_search),
     64                     np.int32(grid[0]), np.int32(grid[1]),np.int32(verbose))

TypeError: function takes exactly 6 arguments (7 given)
```

Probably you are aware and already working on it...
Cheers

[Edit]: maybe I messed up the installation... which I did on top of stardist environment and the help some code found in the notebook from [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki). And I use my own data.

**Comment by saskra** [comment] 2021-11-05 08:58
I get the exact same error message and I have not made any changes to code or data. A possible source of error could perhaps be the installed versions of the Python packages. Could you provide a requirements.txt and/or environment.yml to test it again? I could upload my versions of it here if it would be interesting for comparison.

**Comment by loicsauteur** [comment] 2021-11-10 09:29
My impression is that there is something wrong with the splinedist function `non_maximum_suppression` and its call during the visualisation part of the training notebook and also for the prediction notebook.
For you try the requirements.txt and environment.yml (as txt) from my env.

[splinedist_requirements.txt](https://github.com/uhlmanngroup/splinedist/files/7511458/splinedist_requirements.txt)
 
[splinedist.yml.txt](https://github.com/uhlmanngroup/splinedist/files/7511473/splinedist.yml.txt)

Good luck and let me know if you find something.

**Comment by saskra** [comment] 2021-11-10 09:46
Thanks for this! I'm just afraid that this is not directly comparable because you use Windows and I use Ubuntu Linux. (In fact, I don't see any indication on which operating systems Splinedist has been tested by its creators). Nevertheless, attached are my corresponding files, even though those of the original authors would of course be much more interesting. At least we can see that we have already tested two different versions of Tensorflow and Stardist, among others, and that they all came up with the same error.

[requirements.txt](https://github.com/uhlmanngroup/splinedist/files/7511590/requirements.txt)

```YAML
name: splinedist
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - abseil-cpp=20210324.2=h2531618_0
  - absl-py=0.13.0=py38h06a4308_0
  - aiohttp=3.7.4.post0=py38h7f8727e_2
  - alsa-lib=1.2.3=h516909a_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38h06a4308_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=2.17=openblas
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1.32=h86fa8c9_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py38h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.4.0=hca11adc_0
  - flatbuffers=1.12.0=h2531618_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.2=h36276a3_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h23475e2_0
  - grpc-cpp=1.39.1=h850795e_1
  - grpcio=1.39.0=py38hdd6454d_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - harfbuzz=2.8.1=h83ec7ef_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py38h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - ipykernel=6.4.1=py38h06a4308_1
  - ipython=7.29.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jasper=1.900.1=hd497a04_4
  - jbig=2.1=hdba287a_0
  - jedi=0.18.0=py38h06a4308_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.79.1=h2574ce0_1
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.2=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm11=11.1.0=h3826bc1_0
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.10=h5a2b251_0
  - libopencv=4.5.3=py38h5627943_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_3
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - multidict=5.1.0=py38h27cfd23_2
  - mysql-common=8.0.27=ha770c72_1
  - mysql-libs=8.0.27=hfa10184_1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nccl=2.11.4.1=hdc17891_0
  - ncurses=6.3=heee7806_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.4.5=py38h06a4308_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.71=hb5efdd6_0
  - numpy=1.19.2=py38h6163131_0
  - numpy-base=1.19.2=py38h75fe3a5_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - opencv=4.5.3=py38h578d9bd_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.16.0=py38h709712a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-opencv=4.5.3=py38he5a9106_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pyzmq=22.2.1=py38h295c915_1
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - re2=2021.09.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py38hc65b3f8_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py38hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.6.0=cuda112py38hbe5352d_2
  - tensorflow-base=2.6.0=cuda112py38heae9c4c_2
  - tensorflow-estimator=2.6.0=cuda112py38hb2194ef_2
  - tensorflow-gpu=2.6.0=cuda112py38h0bbbad9_2
  - termcolor=1.1.0=py38h06a4308_1
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha4553b6_1
  - pip:
    - csbdeep==0.6.3
    - cycler==0.11.0
    - h5py==2.10.0
    - imageio==2.10.3
    - keras==2.6.0
    - kiwisolver==1.3.2
    - llvmlite==0.37.0
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numba==0.54.1
    - pillow==8.4.0
    - pyparsing==3.0.5
    - pywavelets==1.2.0
    - scikit-image==0.18.3
    - stardist==0.7.3
    - tifffile==2021.11.2
    - tqdm==4.62.3
```

**Comment by loicsauteur** [comment] 2021-11-18 14:28
Hi @saskra,
I got it to work on my Windows machine. Sorry for not sharing the requirement.txt file.
Here what I installed in a fresh environment:

First, create a anaconda python 3.7 env, **install git** (done via anaconda UI) and start a cmd.
Second, cd to the working folder (i.e. where your data will be, running trainings etc. It will require the splinedist cloned directory folder present there).

Install following stuff:

**pip install --upgrade numpy
pip install tifffile
pip install csbdeep
pip install -e git://github.com/stardist/stardist.git@0.6.2#egg=stardist**

_→ install pyopencl_
_This is machine dependent. In my case (for windows):
download a wheel (for the Win version and matching python version) to your current working directory: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl
and use: **pip install "pyopencl-2021.2.9+cl21-cp37-cp37m-win_amd64.whl"**_

**pip install gputools
pip install edt
pip install wget
pip install fpdf
pip install PTable
git clone https://github.com/uhlmanngroup/splinedist**


_→   to make sure that jupyter is using the proper python environment (or kernel):_
**conda install -c conda-forge notebook**

**pip install packaging**
_cd to splinedist folder_
**python setup.py install
python splinegenerator.py install**

_correct the numpy version (nube needs numpy<=1.20) if you get a warning - This may be OS dependent_
**pip install numpy==1.20**

_The following dependencies are probably more for running the notebooks provided by [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic), but wont hurt installing..._
**pip install opencv-python
pip install pandas
pip install sklearn
pip install astropy
pip install ipywidgets
pip install tabulate**

---

Generally I run into the problem that for prediction it did not find the `phi_16.npy` and `grid_16.npy` files.
I could overcome that by coping those files (from the model folder) to the current working diretory.

**Comment by sohmandal** [comment] 2021-11-22 16:24
Hello @loicsauteur, hello @saskra, thank you for your interest in SplineDist. My apologies for the late response on this issue. You have been absolutely right, the issue has been due to the incompatibility of the current version of SplineDist with the new versions of the StarDist package. In a fresh environment, could you please `pip install stardist==0.6.2`, and then try SplineDist. I have updated the `readme` now mentioning the same solution. Please let me know if this does not sort out the issue.

**Comment by saskra** [comment] 2021-11-23 09:49
Thank you, that was the solution to this error! 

However, I now have the next problem: If I install Stardist via pip and Tensorflow via Conda, then again something does not seem to match from the versions. However, when I install Tensorflow via pip, I am missing packages like cudatoolkit, cudnn and cupti, which are not available with pip. Unfortunately I can't change their permanently installed variants on the server, so I would like to install them only locally in the conda environment. So a complete requirements.txt or environment.yml including the version numbers of tensorflow etc. would be helpful for me.

**Comment by sohmandal** [comment] 2021-11-23 11:53
Here is the `environment.yml` file. Hope this helps. 

[environment.yml.txt](https://github.com/uhlmanngroup/splinedist/files/7587717/environment.yml.txt)

**Comment by saskra** [comment] 2021-11-23 12:23
Thanks, that works!

**Comment by sohmandal** [comment] 2021-11-29 03:27
Closing this issue now. Please feel free to reopen it, if the issue is still not solved.

**Closed by sohmandal** 2021-11-29 03:27 UTC
